### ISSUE TITLE
Clients for KieServerClientServiceImpl

### ISSUE THREAD

**Issue by sutaakar** [jesuino/kie-server-clients#4]
Hi William,

Jus one side note about https://github.com/jesuino/kie-server-clients/blob/master/kie-server-fx-app/src/main/java/org/fxapps/service/KieServerClientServiceImpl.java#L79#L80 . Those jobClient and queryClient are part of BPM capability, so I think their instantiation should be moved to same place where are processesClient and userTasksClient.

**Comment by jesuino** [comment]
Thanks, I have just adjusted it!
